package docs

import (
	"os"
	"path/filepath"
	"testing"
)

// shippedCorePackDir is the repository's own content pack, relative to this package.
const shippedCorePackDir = "../../packs/core"

// requireShippedCorePack skips the calling test when the shipped pack's database is
// absent.
//
// The database is a build product: it is generated by scripts/build-core-pack.mjs
// from packs/core/content/*.mjs and is deliberately not tracked, so a fresh clone
// does not have it until the pack is built. Failing here would mean `go test ./...`
// could not pass on a clean checkout, which is a worse outcome than skipping - CI
// builds the pack first, so these tests do run where it matters.
func requireShippedCorePack(t *testing.T) string {
	t.Helper()

	dbPath := filepath.Join(shippedCorePackDir, "docs.db")
	if _, err := os.Stat(dbPath); err != nil {
		t.Skipf("shipped pack not built (%v); run `pnpm pack:build:core`", err)
	}
	return dbPath
}
